name: project_2359
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

license: 'AGPL-3.0-or-later'

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^6.3.3
  llm_json_stream: ^0.4.7
  lucide_icons: ^0.257.0
  flutter_displaymode: ^0.7.0
  file_picker: ^10.3.8
  flutter_heatmap_calendar: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
