name: project_2359
description: "Project 2359 - A modern study companion app"
homepage: https://github.com/ComsIndeed/project_2359
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.10.1

dependencies:
  collection: ^1.19.1
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.5.0
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_displaymode: ^0.7.0
  font_awesome_flutter: ^10.12.0
  fsrs: ^2.0.1
  google_fonts: ^8.0.0
  moment_dart: ^5.3.0+1
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  sqlite3_flutter_libs: ^0.5.41
  sqlite3_web: ^0.4.1
  supabase_flutter: ^2.12.0
  syncfusion_flutter_core: ^32.2.4
  syncfusion_flutter_pdf: ^32.2.4
  syncfusion_flutter_pdfviewer: ^32.2.4
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.10.4
  drift_dev: ^2.30.0
  build_web_compilers: ^4.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
