name: project_2359
description: "Project 2359 - A modern study companion app"
homepage: https://github.com/ComsIndeed/project_2359
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  collection: ^1.19.1
  drift: ^2.30.0
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.7.0
  flutter_riverpod: ^3.1.0
  fsrs: ^2.0.1
  moment_dart: ^5.3.0+1
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.5.4
  sqlite3_flutter_libs: ^0.5.41
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.10.4
  drift_dev: ^2.30.0
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0
  custom_lint: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
