name: project_2359
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.3

license: 'AGPL-3.0-or-later'

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^6.3.3
  llm_json_stream: ^0.4.7
  lucide_icons: ^0.257.0
  flutter_displaymode: ^0.7.0
  file_picker: ^10.3.8
  flutter_heatmap_calendar: ^1.0.5
  isar: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  windows:
    generate: true
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#0000FF"
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
